#pragma once

#define CONTEXT_ALL_OJP 0xFFFFFFFF
#define CONTEXT_NORMAL_OJP 1
#define CONTEXT_NEARBYITEM_OJP 2
#define CONTEXT_CTFREDTEAM_OJP 4
#define CONTEXT_CTFBLUETEAM_OJP 8
#define CONTEXT_REPLY_OJP 16
#define CONTEXT_HARVESTERREDTEAM_OJP 128
#define CONTEXT_HARVESTERBLUETEAM_OJP 256
#define CONTEXT_NAMES_OJP 1024
